version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 1 # 慣れてきたら上限2〜3に変更（最終的にはweekly）

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 1
