inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6 # TODO: update version if update Ruby
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.github/workflows/**/*.yml'
