name: Ruby Setup

inputs:
  ruby_version:
    description: 'The Ruby version to use'
    required: true

runs:
  using: 'composite'
  steps:
    # nokogiriのビルド用依存パッケージをインストール
    - name: Install build tools for nokogiri
      shell: bash 
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          patch \
          zlib1g-dev \
          liblzma-dev \
          pkg-config \
          libxml2-dev \
          libxslt-dev

    # Set up Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      env:
        # hotfix: bundlerにRubyプラットフォームを強制
        BUNDLE_FORCE_RUBY_PLATFORM: '1'
      with:
        ruby-version: ${{ inputs.ruby_version }} # fileで.ruby-versionを指定すると認識されなかった
        bundler-cache: true # vendor/bundleを自動的にキャッシュ
